package interfaz;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import logica.Controlador;
import logica.Usuario;

public class EditarDatos extends javax.swing.JFrame {

    Controlador controlador = null;
    int idUsuarioReal;
    Usuario usuario;
    
    public EditarDatos(int idUsuarioReal) {
        controlador = new Controlador();
        initComponents();
        this.idUsuarioReal = idUsuarioReal;
        rellenarCampos(idUsuarioReal);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFields = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtContrasena = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setForeground(new java.awt.Color(0, 0, 0));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Cantora One", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 0));
        jLabel5.setText("Edición de Usuarios");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/leaf-icon.png"))); // NOI18N
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cantora One", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 0));
        jLabel2.setText("DiFoglia");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cantora One", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 0));
        jLabel3.setText("Florería");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/leaves-border-3-710.png"))); // NOI18N
        jLabel8.setText("jLabel7");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -200, -1, 370));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/water-drops-300.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        bg.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 460, 270));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bottom-flower-border-715.png"))); // NOI18N
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, -1));

        txtFields.setBackground(new java.awt.Color(0, 51, 0));
        txtFields.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Cantora One", 1, 32)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Usuario");
        txtFields.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Cantora One", 1, 32)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Rol Asignado");
        txtFields.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtFields.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 221, -1));

        btnLimpiar.setBackground(new java.awt.Color(51, 153, 0));
        btnLimpiar.setFont(new java.awt.Font("Cantora One", 1, 24)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        txtFields.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 122, -1));

        btnGuardar.setBackground(new java.awt.Color(51, 153, 0));
        btnGuardar.setFont(new java.awt.Font("Cantora One", 1, 24)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        txtFields.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 111, -1));

        txtContrasena.setBackground(new java.awt.Color(255, 255, 255));
        txtContrasena.setForeground(new java.awt.Color(0, 0, 0));
        txtFields.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 221, -1));

        jLabel13.setFont(new java.awt.Font("Cantora One", 1, 32)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Contraseña");
        txtFields.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        cmbRol.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Administrador" }));
        txtFields.add(cmbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        bg.add(txtFields, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 470, 250));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Leaf-500.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LeavesBG-750.png"))); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        String mensaje = "";

        String nombreUsuario = txtUsuario.getText();
        String contrasenaUsuario = String.valueOf(txtContrasena.getText());

        mensaje = controlador.validarUsuario(nombreUsuario, contrasenaUsuario);

        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        limpiarCajas();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void limpiarCajas() {
        txtUsuario.setText("");
        txtContrasena.setText("");
        cmbRol.setSelectedIndex(0);
    }
    
    private void rellenarCampos(int idUsuarioSeleccionado) {
        
        this.usuario = controlador.traerUsuarioSeleccionado(idUsuarioSeleccionado);
        
        // Conseguimos los datos a 'gettear', y luego pasamos al controlador de la lógica
        // los datos del objeto Usuario, y los atributos a settear posteriormente
        
        String usuarioNombre = usuario.getNombreUsuario();
        String usuarioContrasena = usuario.getContrasena();
        
        // Pedimos que el usuarioRol sea un int, que represente el ID del rol solicitado.
        // Si es 0 + 1 = 1, es USUARIO, si es 1 + 1 = 2, es ADMINISTRADOR
        int idUsuarioRol = (cmbRol.getSelectedIndex() + 1);
        
        // Pasamos al controlador los datos correspondientes...
        
        // Hay que validar de que el nombre de usuario por el que se va a cambiar, no exista ya
        // en la BBDD, se tiene que hacer a nivel de la LÓGICA, no de la interfaz.
        
        ArrayList<Usuario> listaDeUsuarios = controlador.traerUsuarios();
        
        for (Usuario usuario : listaDeUsuarios) {
            if (!usuario.getNombreUsuario().equals(usuarioNombre)) {

                controlador.editarUsuarioSeleccionado(usuario, usuarioNombre, usuarioContrasena, idUsuarioRol);

                // Dejamos un mensajito...
                JOptionPane.showMessageDialog(null, "Usuario editado exitosamente");
                
            } else {
                
                // Dejamos mensajito de error o de advertencia
                JOptionPane.showMessageDialog(null, 
                        "No se puede editar un usuario para que tenga el mismo nombre que otro",
                        "Error", JOptionPane.ERROR_MESSAGE);
                
                break;
            }
        }
        
        limpiarCajas();
        
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JPanel txtFields;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
