package interfaz;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Controlador;
import logica.Usuario;

public class MenuAdmins extends javax.swing.JFrame {

    Controlador controlador = null;
    
    public MenuAdmins() {
        controlador = new Controlador();
        this.setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnCargar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuariosAdmin = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Cantora One", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Panel de Admins");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cantora One", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DiFoglia");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/leaf-blanco.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/florista-4-125.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Cantora One", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Florería");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sunflower-130.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/grass-path-920.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -120, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 920, 130));

        jPanel3.setBackground(new java.awt.Color(255, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCargar.setBackground(new java.awt.Color(51, 153, 0));
        btnCargar.setFont(new java.awt.Font("Cantora One", 1, 36)); // NOI18N
        btnCargar.setForeground(new java.awt.Color(255, 255, 255));
        btnCargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recycle.png"))); // NOI18N
        btnCargar.setText("Cargar");
        btnCargar.setDefaultCapable(false);
        btnCargar.setIconTextGap(6);
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 230, -1));

        btnRegistrar.setBackground(new java.awt.Color(51, 153, 0));
        btnRegistrar.setFont(new java.awt.Font("Cantora One", 1, 36)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add-person.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setDefaultCapable(false);
        btnRegistrar.setIconTextGap(6);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 230, -1));

        btnEditar.setBackground(new java.awt.Color(51, 153, 0));
        btnEditar.setFont(new java.awt.Font("Cantora One", 1, 36)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setDefaultCapable(false);
        btnEditar.setIconTextGap(6);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 230, -1));

        btnEliminar.setBackground(new java.awt.Color(51, 153, 0));
        btnEliminar.setFont(new java.awt.Font("Cantora One", 1, 36)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete-person.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setDefaultCapable(false);
        btnEliminar.setIconTextGap(6);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 230, -1));

        tblUsuariosAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblUsuariosAdmin);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/florista-3.png"))); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 50, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/petals-1050.png"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, -190, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 910, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        cargarTabla();
        
    }//GEN-LAST:event_formWindowOpened

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed

        cargarTabla();

    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
       
        CargarDatos pantallaCargarDatos = new CargarDatos();
        pantallaCargarDatos.setVisible(true);
        pantallaCargarDatos.setLocationRelativeTo(null);
        pantallaCargarDatos.setDefaultCloseOperation(HIDE_ON_CLOSE);
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        if (tblUsuariosAdmin.getRowCount() > 0) {
            if (tblUsuariosAdmin.getSelectedRow() != -1) {
                
                int idProvisorio = Integer.parseInt(String.valueOf(tblUsuariosAdmin.getValueAt(tblUsuariosAdmin.getSelectedRow(), 0)));
                
                Usuario usuarioSeleccionado = controlador.traerUsuarioSeleccionado(idProvisorio);
                
                int idUsuarioReal = usuarioSeleccionado.getId();
                
                 // Le pasamos el id asociado encontrado y seleccionado
        
                EditarDatos pantallaEditarDatos = new EditarDatos(idUsuarioReal);
                pantallaEditarDatos.setVisible(true);
                pantallaEditarDatos.setLocationRelativeTo(null);
                pantallaEditarDatos.setDefaultCloseOperation(HIDE_ON_CLOSE);
                
                cargarTabla();
                
            }
        }
    

        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       
        // Primero verificamos que la tabla no esté vacía
        
        if (tblUsuariosAdmin.getRowCount() > 0) {
            
            // Verificamos que hayamos seleccionado un registro
            
            if (tblUsuariosAdmin.getSelectedRow() != -1) {
                
                // Conseguimos el valor convertido a String de lo seleccionado en la tabla
                
                int numeroRegistroTabla = Integer.parseInt(String.valueOf(tblUsuariosAdmin.getValueAt(tblUsuariosAdmin.getSelectedRow(), 0)));
                
                // Éste valor luego se lo pasamos alcontrolador para que devuelva el objeto real
                
                Object[] opciones = {"Si", "No"};
                
                int resultado = JOptionPane.showOptionDialog(null, 
                        "¿Está seguro de querer eliminar al usuario?",
                        "Confirmación - Eliminación de Usuario", 
                        JOptionPane.YES_NO_OPTION, 
                        JOptionPane.QUESTION_MESSAGE, 
                        null, opciones, opciones[0]);
                
                // En función a la respuesta obtenida, hacemos:
                
                if (resultado == JOptionPane.YES_OPTION) {
                    
                    Usuario usuario = controlador.traerUsuarioSeleccionado(numeroRegistroTabla);
                    
                    // Conseguimos el ID del usuario seleccionado...
                    
                    int idUsuario = usuario.getId();
                    
                    // Mandamos a eliminar al usuario cuyo ID ha sido curado y es el cierto
                    
                    JOptionPane.showMessageDialog(null, "Usuario Eliminado: " + usuario.toString());
                    
                    controlador.eliminarUsuarioSeleccionado(idUsuario);
                    
                    cargarTabla();
                    
                    
                } else {
                    
                    JOptionPane.showMessageDialog(null, "Error - No se seleccionó ningún usuario", 
                            "Error", JOptionPane.ERROR_MESSAGE);
                    
                }
                
            }
            
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuariosAdmin;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla() {

        DefaultTableModel modeloTabla = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };
        
        String[] camposTabla = {"ID", "Nombre de Usuario", "Rol"};
        
        modeloTabla.setColumnIdentifiers(camposTabla);
        
        tblUsuariosAdmin.setModel(modeloTabla);
        
        // Traemos la lista de usuarios
        
        ArrayList<Usuario> listaDeUsuarios = controlador.traerUsuarios();
        
        // Recorremos
        
        if (tblUsuariosAdmin.getRowCount() > 0) {
            for (Usuario usuario : listaDeUsuarios) {
                Object[] registroUsuario = {usuario.getId(), usuario.getNombreUsuario(), usuario.getRolUsuario()};
                
                modeloTabla.addRow(registroUsuario);
                
            }
        }
        
        
        
        
        
    }
}
